name: Build

on:
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "package-lock.json"
      - "package.json"
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "package-lock.json"
      - "package.json"

jobs:
  build:
    name: Build action
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install NPM packages
        run: npm ci
      -
        name: Build JS (development)
        run: npm run-script dev
      -
        name: Setup PHP 5.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.3'
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Test (should fail)
        id: fail01
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail01.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail)
        id: fail02
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          include: |
            broken-without-extension
          exclude: |
            bar
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail02.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail on PHP < 8.3)
        id: fail03
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail03.outcome == 'success'
        run: exit 1
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            bar/foo.php
            broken.php
          debug: true
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          support-duplicated-names: true
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php5.3
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php5.3
          fail-on-warnings: false
          debug: true
      -
        name: Test with warnings (should fail)
        id: fail-warn-1
        continue-on-error: true
        uses: ./
        with:
          directory: test/warnings/php5.3
          fail-on-warnings: true
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail-warn-1.outcome == 'success'
        run: exit 1
      -
        name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: none
      -
        name: Test (should fail)
        id: fail11
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail11.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail)
        id: fail12
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          include: |
            broken-without-extension
          exclude: |
            bar
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail12.outcome == 'success'
        run: exit 1
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          debug: true
      -
        name: Clone a fairly big PHP project
        run: |
          rm -rf /tmp/big-project
          mkdir -p /tmp/big-project
          curl -sSLf -o- https://codeload.github.com/concretecms/concretecms/tar.gz/refs/tags/9.3.7 | tar -xz -C /tmp/big-project --strip-components=1
      -
        name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: none
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: /tmp/big-project
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php8.4
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php8.4
          fail-on-warnings: false
          debug: true
      -
        name: Test with warnings (should fail)
        id: fail-warn-2
        continue-on-error: true
        uses: ./
        with:
          directory: test/warnings/php8.4
          fail-on-warnings: true
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail-warn-2.outcome == 'success'
        run: exit 1
      -
        name: Build JS
        run: npm run-script prod
      -
        name: Copy assets
        run: cp src/checker.php dist/
      -
        name: Check changes
        if: github.event_name == 'push'
        id: changes-check
        run: |
          GIT_OUTPUT="$(git status --porcelain ./dist)"
          if [ -n "$GIT_OUTPUT" ]; then
            printf 'Changes detected:\n%s\n' "$GIT_OUTPUT"
            CHANGES=y
          else
            echo 'No changes detected'
            CHANGES=n
          fi
          echo "detected=$CHANGES" >>"$GITHUB_OUTPUT"
      -
        name: Commit changes
        if: github.event_name == 'push' && steps.changes-check.outputs.detected == 'y' 
        run: |
          git config user.name 'GitHub Action bot'
          git config user.email 'michele@locati.it'
          git add --all dist
          git commit -m 'Automatic build'
          git push
