name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - dev
      - v*
    tags-ignore:
      - "**"
  workflow_dispatch:

jobs:

  check-dist:
    name: Check dist folder
    runs-on: ubuntu-latest
    steps:
      -
        name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        run: npm ci
      -
        name: Build dist
        run: npm run-script build
      -
        name: Check changes
        run: |
          if ! git diff --quiet; then
            echo "::error::Changes detected in dist folder. Please run 'npm run build' and commit the changes before pushing"
            git diff --name-only
            exit 1
          fi

  check-php-syntax:
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '5.3'
          - '8.5'
    name: Check PHP ${{ matrix.php-version }} syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Check syntax
        uses: ./
        with:
          directory: src
          fail-on-warnings: true

  test-repo:
    name: Tests in repo
    needs:
      - check-dist
      - check-php-syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Setup PHP 5.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.3'
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Test (should fail)
        id: fail01
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail01.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail)
        id: fail02
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          include: |
            broken-without-extension
          exclude: |
            bar
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail02.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail on PHP < 8.3)
        id: fail03
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail03.outcome == 'success'
        run: exit 1
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            bar/foo.php
            broken.php
          debug: true
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          support-duplicated-names: true
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php5.3
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php5.3
          fail-on-warnings: false
          debug: true
      -
        name: Test with warnings (should fail)
        id: fail-warn-1
        continue-on-error: true
        uses: ./
        with:
          directory: test/warnings/php5.3
          fail-on-warnings: true
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail-warn-1.outcome == 'success'
        run: exit 1
      -
        name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: none
      -
        name: Test (should fail)
        id: fail11
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail11.outcome == 'success'
        run: exit 1
      -
        name: Test (should fail)
        id: fail12
        continue-on-error: true
        uses: ./
        with:
          directory: test/common
          include: |
            broken-without-extension
          exclude: |
            bar
            broken.php
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail12.outcome == 'success'
        run: exit 1
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: test/common
          exclude: |
            broken.php
          debug: true
      -
        name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: none
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php8.4
          debug: true
      -
        name: Test with warnings (should pass)
        uses: ./
        with:
          directory: test/warnings/php8.4
          fail-on-warnings: false
          debug: true
      -
        name: Test with warnings (should fail)
        id: fail-warn-2
        continue-on-error: true
        uses: ./
        with:
          directory: test/warnings/php8.4
          fail-on-warnings: true
          debug: true
      -
        name: Stop if execution was successful
        if: steps.fail-warn-2.outcome == 'success'
        run: exit 1

  test-remote:
    name: Tests with dist
    needs:
      - check-dist
      - check-php-syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: none
      -
        name: Download action
        run: |
          curl -sSLf -o- \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            'https://api.github.com/repos/${{ github.repository }}/tarball/${{ github.ref }}' \
            | tar -xz --strip-components=1
      -
        name: Clone a fairly big PHP project
        run: |
          mkdir -p /tmp/big-project
          curl -sSLf -o- https://codeload.github.com/concretecms/concretecms/tar.gz/refs/tags/9.3.7 | tar -xz -C /tmp/big-project --strip-components=1
      -
        name: Test (should pass)
        uses: ./
        with:
          directory: /tmp/big-project
          debug: true
